CREATE OR REPLACE PROCEDURE CRMII.FUNC_GET_YYB_GWYH(I_YYB NUMBER, I_ROLE NUMBER)
  RETURN VARCHAR2 IS
  V_YH    VARCHAR2(30);
  V_COUNT NUMBER(8);
  /*20170928 wujun  获取营业部某岗位用户*/
BEGIN
  SELECT COUNT(1)
    INTO V_COUNT
    FROM LBMEMBER A
   WHERE A.ROLEID = I_ROLE
     AND A.ORGID = I_YYB
     AND A.AUDITFLAG = 1;
  IF V_COUNT > 0 THEN
    SELECT WM_CONCAT_11G(A.USERID)
      INTO V_YH
      FROM LBMEMBER A
     WHERE A.ROLEID = I_ROLE
       AND A.ORGID = I_YYB
       AND A.AUDITFLAG = 1;
  ELSE
    SELECT WM_CONCAT_11G(A.USERID)
      INTO V_YH
      FROM LBMEMBER A
     WHERE A.ROLEID = I_ROLE
       AND A.ORGID = (SELECT FID FROM LBORGANIZATION WHERE ID = I_YYB)
       AND A.AUDITFLAG = 1;
  END IF;
  RETURN V_YH;
END;